name: Gradle build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk 
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: setup gradle properties
        run: |
          echo "gpr.user=${{ secrets.PACKAGES_USER }}" >> gradle.properties
          echo "gpr.key=${{ secrets.PACKAGES_TOKEN }}" >> gradle.properties
          
      - name: build
        run: ./gradlew build
        env:
          PACKAGES_USER: ${{ secrets.PACKAGES_USER }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
